U3 verfuegbarkeit pruefen
Lammer-FH/boutique-hotel-technikum-2023-gruppe-e-1 pull request #17
Opened 2023-11-10 16:59 UTC by 11haindl

2023-11-10 17:02 UTC, MGroegerAT commented
Bestätigen Button in Buchen - Zimmer auswählen fehlt

2023-11-10 17:06 UTC, Aentoni requested changes
Anzeige, dass keine Zimmer verfügbar sind fehlt

2023-11-10 17:09 UTC, MGroegerAT requested changes
RoomId wird nicht an BookingView zurückgegeben

2023-11-10 17:31 UTC, Aentoni approved these changes
durch commit erfüllt

2023-11-10 17:31 UTC, Aentoni commented on src/views/BookingView.vue
> +    handleAvailabilityData(data) {
data.numberOfPersons fehlt

2023-11-13 08:49 UTC, MGroegerAT approved these changes
Requested Change umgesetzt

2023-11-13 08:49 UTC, merged